(function(g){var window=this;'use strict';var X3=function(a){a.ma("cardstatechange",a.dj()&&a.Hn()?1:0)},Y3=function(a,b){var c=g.Ia(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},y9a=function(a){var b=g.Kl(a);
a=g.Nl(a);return new g.ul(b.x,b.y,a.width,a.height)},z9a=function(a){return Math.pow(a,3)},A9a=function(a){return 3*a*a-2*a*a*a},a4=function(a){a=g.Ma(a);
delete Z3[a];g.Pc(Z3)&&$3&&$3.stop()},C9a=function(){$3||($3=new g.fo(function(){B9a()},20));
var a=$3;a.isActive()||a.start()},B9a=function(){var a=g.Qa();
g.Bc(Z3,function(b){D9a(b,a)});
g.Pc(Z3)||C9a()},b4=function(a,b,c,d){g.zo.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},D9a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;E9a(a,a.progress);1==a.progress?(a.j=0,a4(a),a.onFinish(),a.aq()):a.Xc()&&a.GH()},E9a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},F9a=function(a,b){g.db.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},c4=function(a,b,c,d,e){b4.call(this,b,c,d,e);
this.element=a},G9a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
c4.call(this,a,b,c,d,e)},H9a=function(a){g.C.call(this);
this.u=a||window;this.j=[]},d4=function(a){return a.baseUrl||null},e4=function(a,b){return g.xm(g.Fg(a,b),function(c){return!!c})},I9a=function(a,b,c){function d(T){var da=T.hovercardButton;
if(!da)return null;da=da.subscribeButtonRenderer;if(!da)return null;var M=f(da.unsubscribedButtonText),qa=f(da.subscribedButtonText);if(da.subscribed){var la=f(da.subscriberCountWithUnsubscribeText);var wa=f(da.subscriberCountText)}else la=f(da.subscriberCountText),wa=f(da.subscriberCountWithSubscribeText);var Ga=null;if(T.signinEndpoint){Ga=Y3(T,"signinEndpoint","webNavigationEndpointData","url");if(!Ga){var Xa,za;Ga=null==(za=g.N(null==(Xa=da.signInEndpoint)?void 0:Xa.commandMetadata,g.S2))?void 0:
za.url}if(!Ga)return null}return M&&(qa||Ga)?{subscribed:da.subscribed,subscribeText:M,subscribeCount:la,unsubscribeText:qa,unsubscribeCount:wa,enabled:da.enabled,signinUrl:Ga,classic:T.useClassicSubscribeButton}:null}
function e(T){if(T){var da=[],M=T.videoId;M&&da.push("v="+M);(M=T.playlistId)&&da.push("list="+M);(T=T.startTimeSeconds)&&da.push("t="+T);return"/watch?"+da.join("&")}}
function f(T){if(!T)return null;var da=T.simpleText;return da?da:T.runs?g.Fg(T.runs,function(M){return M.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,v=null,x=null,z=!1,B=null,E=null,G=null,F=null,K=null,P=null;if("VIDEO"===h)g.N(l,g.aJ)?m=g.N(l,g.aJ).url:(P=g.N(l,g.ZI),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.N(l,g.aJ)?m=g.N(l,g.aJ).url:(P=g.N(l,g.ZI),m=e(P)),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
h){if(z=Y3(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=Y3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=Y3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=Y3(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,
Y="";if(b.metadata){var U=f(b.metadata);U&&(Y=U)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Y,callToAction:f(b.callToAction),HR:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,isLiveVideo:p,playlistLength:v,channelId:x,subscribeButton:B,subscribersText:E,isSubscribe:z,targetUrl:m||null,A2:n,sessionData:Q?{itct:Q}:null,r7:q,Sz:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:e4(b.impressionUrls||[],d4),l2:e4(b.hovercardShowUrls||[],d4),clickUrls:e4(l.loggingUrls||[],d4),visualElement:g.lC(b.trackingParams),productPrice:F,additionalFeesText:K,watchEndpoint:P||null}},J9a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:e4(a.impressionUrls||[],d4),elements:e4(a.elements||[],function(d,e){return I9a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.lC(a.trackingParams));return c},K9a=function(a){g.gR.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.T=g.HH(a)||"profilepage"===a.Aa;this.ea=a.experiments.gb("web_rounded_thumbnails");this.events=new g.GF(this);g.D(this,this.events);this.events.N(this.player,g.HB("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.IB("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.Db);this.events.N(window,"focus",this.i6);this.load();var b=g.He("STYLE");(g.ve("HEAD")[0]||
document.body).appendChild(b);g.ab(this,function(){g.Me(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},L9a=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},f4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},M9a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=J9a(f,L9a(a))));g4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Tv;d&&(c.postParams={ad_tracking:d});if(b=g.yBa(b))if(b=g.Id(b),b=g.Gd(b))a.B=g.qw(b,c)},g4=function(a,b,c){c=void 0===c?!0:c;
a.player.Mf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&N9a(a);c=[];d=new g.FB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",K:"ytp-ce-shadow"}),g.yQ(a.player,a.u.element,4),a.C=new g.bO(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=O9a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.yQ(a.player,f.element,4);var h=new g.FB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);P9a(a,
f,e)}else g.jB(new g.tx("buildEndscreenElement null",e))}a.player.De(c);a.Db()}},N9a=function(a){var b=g.oC(),c=g.pC();
c&&b&&a.endscreen.visualElement&&g.rM(c,b,a.endscreen.visualElement)},O9a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ha:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Sz||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-covering-image",X:h4(b)},{G:"div",K:"ytp-ce-covering-shadow-top"},{G:"a",K:"ytp-ce-covering-overlay",X:{href:i4(a,b.targetUrl),tabindex:"-1"},W:[{G:"div",Ha:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Do(b.title||"")},qa:b.title},{G:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={G:"div",Ha:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Sz||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-covering-image",X:h4(b)},{G:"div",K:"ytp-ce-covering-shadow-top"},{G:"a",K:"ytp-ce-covering-overlay",X:{href:i4(a,b.targetUrl),tabindex:"-1"},W:[{G:"div",Ha:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Do(b.title||"")},qa:b.title},{G:"div",K:"ytp-ce-playlist-count",
W:[{G:"div",K:"ytp-ce-playlist-icon"},{G:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ha:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Sz||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",
W:[{G:"div",K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ha:["ytp-ce-channel-title","ytp-ce-link"],X:{href:i4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Do(b.title||"")},qa:b.title},b.subscribeButton?{G:"div",K:"ytp-ce-subscribe-container",W:[{G:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{G:"div",Ha:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:h4(b)}]};c=new g.V(c);var d=g.we(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.no(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.kS(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ha:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Sz||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",
W:[{G:"div",K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",K:"ytp-ce-website-title",X:{dir:g.Do(b.title||"")},qa:b.title},{G:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{G:"a",Ha:["ytp-ce-website-goto","ytp-ce-link"],X:{href:i4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:h4(b)},{G:"div",K:"ytp-ce-expanding-icon",X:Q9a(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={G:"div",K:"ytp-ce-merchandise-price-container",W:[{G:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={G:"div",Ha:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Sz||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},
{G:"div",K:"ytp-ce-expanding-overlay-content",W:[{G:"div",K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",K:"ytp-ce-merchandise-title",X:{dir:g.Do(b.title||"")},qa:b.title},c,{G:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{G:"a",Ha:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:i4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:h4(b)},{G:"div",K:"ytp-ce-merchandise-invideo-cta-container",
W:[{G:"div",K:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.no(c.element,"ytp-ce-placeholder");return c},h4=function(a){if(a.HR)var b=a.HR.thumbnails;
return Q9a(b?b[b.length-1].url:null)},Q9a=function(a){return a?{style:"background-image: url("+a+")"}:{}},P9a=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.no(b.element,"ytp-ce-force-expand"),j4(a,c.id,!0)):(g.po(b.element,"ytp-ce-force-expand"),g.po(b.element,"ytp-ce-element-hover"),j4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){R9a(a,b,c)});
b.Qa("mouseleave",function(){S9a(a,b,c)});
a.player.V().isMobile||b.Qa("click",function(){g.no(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){T9a(a,c,m)});
b.Qa("keypress",function(m){T9a(a,c,m)});
b.Qa("focus",function(){R9a(a,b,c)});
b.Qa("blur",function(){S9a(a,b,c)});
b.Qa("touchstart",function(){R9a(a,b,c)});
var l=g.ye("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.po(b.element,"ytp-ce-element-hover");g.po(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.ye("ytp-sb-subscribe",b.element));d(g.ye("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},T9a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.mo(d,"ytp-ce-element");){g.mo(d,"subscribe-label")&&U9a(a,b);
if(g.mo(d,"ytp-ce-channel-subscribe"))return;d=g.Ne(d)}if(!d||g.mo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])S9a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.r7)U9a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Id(i4(a,b.targetUrl)),g.ZK(g.Gd(c),void 0,b.sessionData);else{var e=g.$H(a.player.V())||a.player.getVideoData().D,f=function(){var h=i4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.cw(h);e&&n&&(n.v||
n.list)?a.player.Xm(n.v,l,n.list,!1,void 0,m||void 0):g.XK(h,l)};
U9a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},i4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.hI(a)+b}else return"";return b},R9a=function(a,b,c){g.mo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.no(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.fo(function(){g.no(b.element,"ytp-ce-element-hover")},200)).start():g.no(b.element,"ytp-ce-element-hover"),k4(a,c.l2),j4(a,c.id,!0))},S9a=function(a,b,c){g.po(b.element,"ytp-ce-element-hover");
g.po(b.element,"ytp-ce-force-expand");j4(a,c.id,!1)},j4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.ro(a.j[e].element,"ytp-ce-element-shadow-show",c)},k4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||f4(a))c&&c();else{b=V9a(a,b);var e=0,f=!1,h=new g.fo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.az(b[a],d)}},U9a=function(a,b,c){k4(a,b.clickUrls,c);
(a=g.pC())&&b.A2&&g.vM(a,b.visualElement)},V9a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(W9a(b[d],c));return a},W9a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},X9a=function(a){return"string"===typeof a?a:""},l4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Y9a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},m4=function(a){return a.value?a.value:null},n4=function(a){if(!a)return null;
var b=g.Id(X9a(a.value));b=g.Gd(b);if(!b)return null;var c=l4(a.target,Z9a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Y9a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$9a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},c$a=function(a){if(!a)return null;
var b=l4(a.type,a$a),c=l4(a.trigger,b$a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=n4(a?a:null);return b?new $9a(b,c,a):null},d$a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},e$a=function(a,b){return g.ib(a.action,b)},f$a=function(a,b){this.context=a;
this.j=b},g$a=function(a){return a.customMessage?o4("div","iv-card-message",a.customMessage):""},p4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",K:"iv-card-image",X:{style:a},W:c}},h$a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(o4("li","",c.value));return{G:"ul",K:"iv-card-meta-info",W:b}},o4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Do(c);return{G:a,X:b,qa:c}},i$a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.cA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.cA+");");c.dir=g.Do(a.customMessage);var d=[{G:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",K:"iv-card-link-icon"}));return{G:"div",Ha:b,X:c,W:d}},q4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.wi.click,5)}},j$a=function(a,b){this.merchant=a;
this.price=b},k$a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},l$a=function(a,b){return b?b:k$a(a)?"current":"new"},r4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.Ya=new Map;this.Wa=new Map;this.context.F.addEventListener(g.HB("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.IB("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)})},s4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.HH(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.wb=!1});
a.context.j.Qa(b,"touchmove",function(){a.wb=!0})},m$a=function(a){var b;
return(null==(b=g.N(a,g.aJ))?0:b.url)?g.N(a,g.aJ).url:(a=g.N(a,g.ZI))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},t4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
jW:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
TG:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},n$a=function(a,b,c){r4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.Ra=this.Rb=this.B=this.isInitialized=!1;this.Aa=null;this.cards=[];this.Gb=this.T=this.Ma=this.D=this.Va=this.j=null;this.ea=[];this.oa=this.J=this.Hf=this.Ka=null;this.I=0;this.Ba=new g.fo(function(){},c.Y.Mg?4E3:3E3);
g.D(this,this.Ba);this.ob=new g.fo(function(){});
g.D(this,this.ob);this.ya=new f$a(c,function(e,f,h,l,m,n){s4(d,e,f,h,l,m,n)});
this.Z=new g.V({G:"div",K:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",K:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",K:"iv-drawer-header-text"},{G:"button",Ha:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{G:"div",K:"iv-drawer-content"}]});g.D(this,this.Z);this.C=this.Z.element;this.ib=new g.bO(this.Z,330);g.D(this,this.ib);this.Tb=g.ye("iv-drawer-header-text",this.C);this.u=g.ye("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&u4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&v4(d)});
this.F.addEventListener("videodatachange",this.Jr.bind(this))},o$a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){u4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){v4(a)});
var c=b.headerText;g.Pe(a.Tb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ka=g.lC(b.trackingParams);a.J=g.lC(b.closeTrackingParams);a.Hf=g.lC(b.iconTrackingParams)},p$a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.PB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,wi:{},In:null,Ek:e.trackingParams?g.lC(e.trackingParams):null,Hf:f&&f.trackingParams?g.lC(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
cA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};w4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.PB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:x4(a,c,b,f),sponsored:!1,wi:t4(f,e,f.command),In:f.trackingParams?g.lC(f.trackingParams):null,Ek:e.trackingParams?g.lC(e.trackingParams):null,Hf:l&&l.trackingParams?g.lC(l.trackingParams):null,imageUrl:y4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.PB(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,cA:null,title:f.title?g.PB(f.title):"",customMessage:f.callToAction?g.PB(f.callToAction):"",url:g.N(f.command,g.aJ).url?n4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.N(f.command,g.aJ).url}):null,onClickCommand:null};w4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.PB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,wi:t4(e,f,e.endpoint),In:e.trackingParams?g.lC(e.trackingParams):null,Ek:f.trackingParams?g.lC(f.trackingParams):null,Hf:l&&l.trackingParams?g.lC(l.trackingParams):null,channelId:g.N(e.endpoint,z4).browseId,customMessage:e.customText?g.PB(e.customText):null,profileImageUrl:y4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.PB(e.channelName):"",metaInfo:[e.subscriberCountText?g.PB(e.subscriberCountText):""],url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.N(e.endpoint,z4).canonicalBaseUrl?g.N(e.endpoint,z4).canonicalBaseUrl:"/channel/"+g.N(e.endpoint,z4).browseId}),onClickCommand:null};w4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.PB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,wi:t4(e,f,e.action),In:e.trackingParams?g.lC(e.trackingParams):null,Ek:f.trackingParams?g.lC(f.trackingParams):null,Hf:l&&l.trackingParams?g.lC(l.trackingParams):null,OC:y4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.PB(e.customMessage):null,playlistVideoCount:g.PB(e.playlistVideoCount),title:e.playlistTitle?g.PB(e.playlistTitle):"",metaInfo:[e.channelName?g.PB(e.channelName):
"",e.videoCountText?g.PB(e.videoCountText):""],url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:m$a(e.action)}),onClickCommand:null};w4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.PB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,wi:t4(e,f,e.action),In:e.trackingParams?g.lC(e.trackingParams):null,Ek:f.trackingParams?g.lC(f.trackingParams):null,Hf:l&&l.trackingParams?g.lC(l.trackingParams):null,OC:y4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.PB(e.lengthString):null,customMessage:e.customMessage?g.PB(e.customMessage):null,title:e.videoTitle?g.PB(e.videoTitle):"",metaInfo:[e.channelName?g.PB(e.channelName):
"",e.viewCountText?g.PB(e.viewCountText):""],isLiveNow:!!e.badge,url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:m$a(e.action)}),onClickCommand:null};w4(a,b)}}}}}a.I++},y4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},x4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},r$a=function(a,b){if(b=q$a(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.card.id),g.Me(b.mJ),g.pb(a.cards,b),a.SD(),A4(a)},u4=function(a,b,c){if(!a.B){a.ib.show();
a.Va=new g.fo(function(){g.no(a.context.F.getRootNode(),g.AW.IV_DRAWER_OPEN)},0);
a.Va.start();a.Aa=g.rz(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.pC();d&&a.Ka&&a.J&&g.tM(d,[a.Ka,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.BT||(f.BT=!0,s$a(a.context.logger,f.card.wi.impression,b)),d&&g.tM(d,[f.card.In]);X3(a.F);c&&(a.D=new g.fo(function(){a.Ma=a.T;a.Gb.focus()},330),a.D.start())}},v4=function(a){a.B&&(a.ib.hide(),g.sz(a.Aa),a.Aa=null,g.po(a.context.F.getRootNode(),g.AW.IV_DRAWER_OPEN),a.B=!1,X3(a.F),a.D&&a.D.stop(),a.D=new g.fo(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},
u$a=function(a){g.oo(a.vb(),[g.AW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.yQ(a.F,a.C,5);t$a(a);a.T=g.ye("ytp-cards-button",a.F.getRootNode());a.Gb=g.ye("iv-drawer-close-button",a.C);a.isInitialized=!0},t$a=function(a){var b=g.ye("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.A0,a);a.context.j.Qa(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Qa(a.u,"scroll",a.O0,a);a.context.u.subscribe("onHideControls",function(){a.Ra=!0});
a.context.u.subscribe("onShowControls",function(){a.Ra=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ra=g.mo(a.F.getRootNode(),"ytp-autohide")});
a.ea.push(g.Lz("iv-button-shown",a.J2,a));a.ea.push(g.Lz("iv-button-hidden",a.I2,a));a.ea.push(g.Lz("iv-teaser-shown",a.SX,a));a.ea.push(g.Lz("iv-teaser-hidden",a.K2,a));a.ea.push(g.Lz("iv-teaser-clicked",a.RX,a))},v$a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.N(b.onClickCommand,g.i6a))?void 0:c.targetId)?(a.oa=b,!0):!1},w$a=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.S("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.cJ(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.N(h[0],g.BMa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
w4=function(a,b){if(!v$a(a,b)||w$a(a,b)){var c=x$a(a,b);
if(c){var d={card:b,mJ:c.element,BT:!1};if(!b.onClickCommand){a.isInitialized||u$a(a);r$a(a,b.id);var e=y$a(a,d);g.xb(a.cards,e,0,d);c.Ea(a.u,e);a.SD()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,A4(a),z$a(a,d),u4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&A$a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){A$a(a,d)}),A4(a))}}},x$a=function(a,b){switch(b.type){case "simple":var c=a.ya;
var d=b.displayDomain?{G:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=i$a(b);d={G:"div",Ha:["iv-card"],W:[{G:"a",K:"iv-click-target",X:{href:b.url?m4(b.url)||"":""},W:[p4(b.imageUrl,d),{G:"div",K:"iv-card-content",W:[o4("h2",void 0,b.title),e]}]}]};d=new g.V(d);q4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.ya;d={G:"div",Ha:["iv-card","iv-card-channel"],W:[{G:"a",Ha:["iv-click-target"],X:{href:m4(b.url)||"","data-ytid":b.channelId},W:[p4(b.profileImageUrl),
{G:"div",K:"iv-card-content",W:[g$a(b),{G:"h2",K:"iv-card-primary-link",qa:b.title},h$a(b)]}]}]};d=new g.V(d);q4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.ya;d={G:"div",Ha:["iv-card","iv-card-playlist"],W:[{G:"a",K:"iv-click-target",X:{href:m4(b.url)||""},W:[p4(b.OC,{G:"div",K:"iv-card-image-overlay",W:[{G:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{G:"div",K:"iv-card-content",W:[g$a(b),o4("h2","iv-card-primary-link",b.title),h$a(b)]}]}]};
d=new g.V(d);q4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.ya;var f=!g.lb(b.offers);d=["iv-card"];e="";var h=i$a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",K:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({G:"div",K:"iv-card-offer-merchant",qa:h.merchant}),h={G:"div",W:f});f=b.url?m4(b.url)||"":"";d={G:"div",Ha:d,X:{tabindex:"0"},W:[{G:"a",Ha:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",K:"iv-card-content",W:[b.sponsored?{G:"div",K:"iv-card-sponsored",W:["Patrocinado",{G:"div",K:"iv-ad-info-container",W:[{G:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{G:"div",K:"iv-ad-info-icon-container",W:[{G:"div",K:"iv-ad-info-icon"},{G:"div",K:"iv-ad-info-callout"}]}]}]}:"",{G:"a",K:"iv-click-target",X:{href:f},W:[o4("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.He("span");g.Pe(e,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
d.Zd(e,"adInfo");q4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.ya;d=b.videoDuration?{G:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{G:"span",Ha:["yt-badge","yt-badge-live"],qa:"EN DIRECTO AHORA"}:null;f={G:"div",Ha:["iv-card","iv-card-video"],W:[{G:"a",K:"iv-click-target",X:{href:(null==(h=b.url)?void 0:m4(h))||""},W:[p4(b.OC,d),{G:"div",K:"iv-card-content",W:[g$a(b),o4("h2","iv-card-primary-link",b.title),h$a(b),e]}]}]};d=new g.V(f);q4(c,
g.xe("iv-click-target",d.element),b,b.url);b=d;break;default:return null}a.F.V().experiments.gb("web_rounded_containers")&&g.no(b.element,"ytp-rounded-info");return b},y$a=function(a,b){if(0===a.cards.length)return 0;
a=g.jb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},B$a=function(a){return a.j?"productListing"===a.j.card.type:g.Mk(a.cards,function(b){return"productListing"===b.card.type})},A4=function(a){g.ro(a.F.getRootNode(),"ytp-cards-shopping-active",B$a(a))},A$a=function(a,b){if(!g.mo(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.pC(),d=a.j?a.j.card.Hf:a.Hf;
c&&d&&g.uM(c,[d]);a.j=b;A4(a)}(c=a.isInitialized&&"none"==a.vb().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.F.Hy(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ob.isActive()||((!a.B||!a.Ba.isActive()&&a.Ra)&&z$a(a,b),a.ob.start(910+b.card.teaserDurationMs))}},z$a=function(a,b){a.Z.ub?(b=new b4([0,
a.u.scrollTop],[0,b.mJ.offsetTop],600,A9a),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.oN(a.Z,!0),a.u.scrollTop=b.mJ.offsetTop,g.oN(a.Z,!1))},B4=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},q$a=function(a,b){return g.ib(a.cards,function(c){return c.card.id===b})},C4=function(a,b,c){r4.call(this,a,b);
this.annotation=c;this.isActive=!1},C$a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},D4=function(a,b,c){C4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},D$a=function(a,b){var c=void 0===c?0:c;
var d=y9a(b).width;g.Il(b,d);c=new G9a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,z9a);g.D(a,c);a.context.B.Qa(c,"begin",function(){g.Ol(b,!0)});
c.play()},G$a=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ha:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({G:"div",Ha:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.kS(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Ea(d));var f=a.createElement({G:"div",Ha:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ha:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ol(h,!1);a.context.Y.S("web_rounded_containers")&&g.no(h,"ytp-rounded-branding-context");var l=a.createElement({G:"div",Ha:["branding-context-container-outer"]});l.appendChild(h);g.Cl(l,"right",b.image_width+"px");g.Je(a.vb(),l);a.B=new g.fo(function(){E$a(a,h,l)},500);
g.D(a,a.B);a.context.j.Qa(a.vb(),"mouseover",function(){F$a(a,h,l,f,b.image_height)});
a.context.j.Qa(a.vb(),"mouseout",function(){a.B.start()})}},F$a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Nl(b);a.j||(b.style.width=g.Hl(f.width,!0),c.style.width=g.Hl(f.width,!0));g.Cl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Cl(d,"right","1px");a.C=!0;g.Ol(b,!0);a.D=new g.fo(function(){g.no(this.vb(),"iv-branding-active")},0,a);
a.D.start()}},E$a=function(a,b,c){g.po(a.vb(),"iv-branding-active");
a.I=new g.fo(function(){g.Ol(b,!1);a.j||(c.style.width=g.Hl(0,!0))},250);
a.I.start();a.C=!1},H$a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},I$a=function(a,b,c){C4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ha:["iv-promo-contents"]});this.D=new g.fo(function(){d.j.setAttribute("aria-hidden","true");g.Ol(d.B,!1);g.Ol(d.u,!0)},700,this);
g.D(this,this.D)},K$a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.vb().setAttribute("aria-hidden","true");a.vb().setAttribute("aria-label","Promoci\u00f3n");a.vb().tabIndex=0;var e=a.annotation.Oe(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ha:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&s4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",K:"iv-promo-txt"}),g.Sd(f,m4(e)),a.j=f):a.j=a.createElement({G:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ha:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ha:["iv-button","iv-promo-button"],W:[{G:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({G:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&s4(a,a.vb(),e,a.annotation.id,b.session_data,void 0,c)}g.no(a.j,"iv-click-target");
e&&s4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",qa:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ha:["yt-badge","iv-promo-badge-live"],qa:"EN DIRECTO AHORA"})),g.no(a.j,"iv-click-target"),e&&s4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",K:"iv-promo-actions"});a.u=a.createElement({G:"button",Ha:["iv-promo-expand","ytp-button"]});a.u.title="Expandir";a.context.j.Qa(a.u,"click",function(q){J$a(a,5E3,q)});
c.appendChild(a.u);g.Ol(a.u,!1);a.context.j.Qa(a.vb(),"mouseover",a.M1,a);a.context.j.Qa(a.vb(),"mouseout",a.L1,a);a.context.j.Qa(a.vb(),"touchend",function(q){J$a(a,5E3,q)});
a.B=a.createElement({G:"button",Ha:["iv-promo-close","ytp-button"]});a.B.title="Cerrar";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.H1:a.G1,a);c.appendChild(a.B);g.oo(a.vb(),d);h&&(g.Je(a.vb(),h),n&&h.appendChild(n));g.Je(a.vb(),a.J);g.Je(a.vb(),c)},J$a=function(a,b,c){c.stopPropagation();
L$a(a);M$a(a,b);a.j.focus()},N$a=function(a){a.isCollapsed||a.T||a.C||(g.no(a.vb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},L$a=function(a){a.D.stop();
a.isCollapsed&&(g.qo(a.vb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ol(a.u,!1),g.Ol(a.B,!0))},M$a=function(a,b){a.C||(a.C=g.rf(function(){O$a(this);
N$a(this)},b,a))},O$a=function(a){a.C&&(g.Ea.clearTimeout(a.C),a.C=null)},P$a=function(a){this.F=a},s$a=function(a,b,c){b&&(c?E4(a,b.map(function(d){return g.Yn(d,c)})):E4(a,b))},E4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.az(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},Q$a=function(a){g.gR.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new P$a(this.player);this.D=new g.GF(this);this.C=this.Mo=null;this.events=new g.GF(this);this.J=this.j=null;this.T=[];g.D(this,this.D);this.D.N(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.N(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.N(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.N(this.player,"resize",function(d){b.ma("resize",d)});
this.D.N(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.TX,this);this.subscribe("resize",this.SF,this);this.player.V().ya.subscribe("vast_info_card_add",this.OU,this);g.D(this,this.events);this.Z=this.createElement({G:"div",K:"video-custom-annotations"});this.u=new g.V({G:"div",Ha:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.yQ(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ha:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({G:"div",K:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.yv()&&this.load();var c=this.createElement({G:"style"});(g.ve("HEAD")[0]||document.body).appendChild(c);g.ab(this,function(){g.Me(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},R$a=function(a){a=a.createElement({G:"div",
Ha:["annotation","annotation-type-custom"]});g.Ol(a,!1);return a},S$a=function(a,b){b=!b.isCued()&&!g.S(b,1024);
g.oN(a.u,b);g.oN(a.B,b)},T$a=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ja(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(T$a(a,e))}return c},X$a=function(a){var b=a.player.getVideoData();
if(b.Ya){var c=a.player.V().ya.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.kw(h)&&h.responseXML?h.responseXML:null)&&U$a(a,h)}};
g.rx()&&(d.onFinish=V$a(a,d.onFinish));d.postParams={ic_only:"1"};W$a(d,c);g.qw(b.Ya,d)}}},W$a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.fA&&(a.postParams.ic_coll=b.fA);b.YD&&(a.postParams.ic_xml=b.YD);b.RC&&(a.postParams.ic_track=b.RC)},Y$a=function(a){var b=new g.V({G:"div"});
g.Ol(b.element,!1);var c=new n$a(a.player,b.element,F4(a));g.D(c,b);b.Ea(a.u.element);c.DC();return c},F4=function(a){if(!a.J){var b=new H9a(a);
g.D(a,b);var c=new g.Gj(a);g.D(a,c);a.J=new H$a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.lj)}return a.J},U$a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)){var e=d[0].getAttribute("itct");if(e&&(d=g.pC())){var f=g.oC();f&&(e=[g.lC(e)],g.Rv("safe_logging_library_killswitch")?g.kM(void 0,d,f,e):g.Xv(g.kM)(void 0,d,f,e))}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){e=T$a(a,b[d]);f=null;try{if(e){var h=e.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=l4(e.type,Z$a),p=l4(e.style,$$a),q=X9a(e.data),r=0!==q.length?JSON.parse(q):{};var v=e.action;e=c$a;if(null==v)var x=null;else if(g.Ia(v)){l=
[];for(var z=g.t(v),B=z.next();!B.done;B=z.next()){var E=e(B.value);E&&l.push(E)}x=l}else{var G=e(v);x=G?[G]:[]}f=m&&n?new d$a(m,n,p,x,r):null}else f=null}catch(U){}if(f)if("branding"===f.type||"promotion"===f.type){e=a;l=f;var F=R$a(e),K=null;switch(l.type){case "branding":if(e.player.V().Cd)break;e.u.element.appendChild(F);K=new D4(F,F4(e),l);break;case "promotion":g.yQ(e.player,F,4),K=new I$a(F,F4(e),l)}K&&K.DC();if(e=K)g.D(a,e),a.I[f.id]=e}else if("card"===f.type||"drawer"===f.type){a.j||(a.j=
Y$a(a),g.D(a,a.j));if("card"===f.type){c=a.j;var P=f&&f.data&&f.data.card_type;e=f.data;if(P)switch(l=e.tracking||{},l={impression:l.impression,click:l.click,close:l.close,jW:l.teaser_impression,TG:l.teaser_click},F=e.tracking_params||{},K=null,P){case "collaborator":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wi:l,In:F.card?g.lC(F.card):
null,Ek:F.teaser?g.lC(F.teaser):null,Hf:F.icon?g.lC(F.icon):null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};w4(c,f);break;case "playlist":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,
sessionData:e.session_data||{},sponsored:e.sponsored||!1,wi:l,In:F.card?g.lC(F.card):null,Ek:F.teaser?g.lC(F.teaser):null,Hf:F.icon?g.lC(F.icon):null,OC:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};w4(c,f);break;case "productListing":e.signin_url&&(K=n4({target:"current",value:e.signin_url}));P=
[];for(var Q=e.offers||[],Y=0;Y<Q.length;Y++)P.push(new j$a(g.oe(Q[Y].merchant),g.oe(Q[Y].price)));f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wi:l,In:F.card?g.lC(F.card):null,Ek:F.teaser?g.lC(F.teaser):null,Hf:F.icon?g.lC(F.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,
cA:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Idb:K,Hdb:e.signin_title?e.signin_title:void 0,Gdb:e.signin_message?e.signin_message:void 0,offers:P,onClickCommand:null};w4(c,f);break;case "simple":f={id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||
!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wi:l,In:F.card?g.lC(F.card):null,Ek:F.teaser?g.lC(F.teaser):null,Hf:F.icon?g.lC(F.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,cA:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};w4(c,f);break;case "video":f=
{id:f.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,wi:l,In:F.card?g.lC(F.card):null,Ek:F.teaser?g.lC(F.teaser):null,Hf:F.icon?g.lC(F.icon):null,OC:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:n4({pause_on_navigation:e.pause_on_navigation,
target:e.target||"new",value:e.url}),onClickCommand:null},w4(c,f)}}else o$a(a.j,f);c=!0}}c&&(X3(a.player),a.SF())},aab=function(a,b){var c=!1;
a.j||(a.j=Y$a(a),g.D(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(p$a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.PB(b.headerText):"",g.Pe(c.Tb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ka=b.trackingParams?g.lC(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.lC(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Hf=b.icon.infoCardIconRenderer.trackingParams?
g.lC(b.icon.infoCardIconRenderer.trackingParams):null,X3(a.player),a.SF())},bab=function(a,b,c,d,e){if(!a.player.V().Cd){var f=[];
b.navigationEndpoint&&g.N(b.navigationEndpoint,z4)&&g.N(b.navigationEndpoint,z4).browseId&&f.push(new $9a("openUrl","click",new Y9a("/channel/"+g.N(b.navigationEndpoint,z4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.N(b.subscribeButton,
g.ZJ)){d.channel_id=g.N(b.subscribeButton,g.ZJ).channelId;var l;b=g.N(b.subscribeButton,g.ZJ);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.PB(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.PB(b.subscriberCountText))):(b.subscriberCountText&&(e=g.PB(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.PB(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.N(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.S2))?void 0:m.url)||"";l={subscribeText:g.PB(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.PB(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new d$a(c,"branding","branding",f,d);l=R$a(a);a.u.element.appendChild(l);f=new D4(l,F4(a),f);f.DC();g.D(f,f);a.I[c]=f}},V$a=function(a,b){return function(){var c=g.xa.apply(0,arguments);
a.isDisposed()||a.T.push(g.ao.Qh(function(){b.apply(null,g.u(c))}))}},cab=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.rQ.prototype.Hy=g.ba(19,function(a,b){var c=g.yR(this.tb());c&&c.Hy(a,b)});
var Z3={},$3=null;g.Ra(b4,g.zo);g.k=b4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Xc())return!1;a4(this);this.startTime=a=g.Qa();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.OF();this.Zk("play");-1==this.j&&this.Zk("resume");this.j=1;var b=g.Ma(this);b in Z3||(Z3[b]=this);C9a();D9a(this,a);return!0};
g.k.stop=function(a){a4(this);this.j=0;a&&(this.progress=1);E9a(this,this.progress);this.Zk("stop");this.aq()};
g.k.pause=function(){this.Xc()&&(a4(this),this.j=-1,this.Zk("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Zk("destroy");b4.qf.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.GH=function(){this.Zk("animate")};
g.k.Zk=function(a){this.dispatchEvent(new F9a(a,this))};
g.Ra(F9a,g.db);g.Ra(c4,b4);c4.prototype.C=function(){};
c4.prototype.GH=function(){this.C();c4.qf.GH.call(this)};
c4.prototype.aq=function(){this.C();c4.qf.aq.call(this)};
c4.prototype.OF=function(){this.C();c4.qf.OF.call(this)};
g.Ra(G9a,c4);G9a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var z4=new g.Rp("browseEndpoint");g.w(H9a,g.C);g.k=H9a.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.rz(a,b,c);this.j.push(a);return a};
g.k.uF=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Ypa(a,b,c);this.j.push(a);return a};
g.k.Dc=function(a){g.sz(a);g.pb(this.j,a)};
g.k.rg=function(){g.sz(this.j);this.j.length=0};
g.k.ra=function(){this.rg();g.C.prototype.ra.call(this)};g.w(K9a,g.gR);g.k=K9a.prototype;g.k.load=function(){g.gR.prototype.load.call(this);if(!f4(this)){var a=g.zBa(this.player.getVideoData());a?(a=J9a(a,L9a(this)),g4(this,a,!1)):M9a(this)}};
g.k.unload=function(){g4(this,null);this.B&&(this.B.abort(),this.B=null);g.gR.prototype.unload.call(this)};
g.k.Zg=function(a,b){return f4(this)?"loadCustomEndscreenRenderer"===a?(a=J9a(b,"new"),g4(this,a),!0):null:null};
g.k.getOptions=function(){return f4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Db=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<dab.length;f++){var h=Math.abs(b.width-dab[f]);if(-1===e||d>=h)e=f,d=h}d=eab[e];this.u&&g.Cl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ml(e.element,m,f);g.Il(e.element,n,p);this.ea&&(g.qo(e.element,fab),256<m||256<f?g.no(e.element,"ytp-ce-large-round"):96<m||96<f?g.no(e.element,"ytp-ce-medium-round"):g.no(e.element,"ytp-ce-small-round"));g.qo(e.element,gab);m=h.left+h.width/2;h=h.top+l/2;g.no(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qo(e.element,eab);g.no(e.element,d);(e=g.we(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Cl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())k4(this,this.endscreen.impressionUrls),(a=g.pC())&&this.endscreen.visualElement&&g.sM(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.no(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.no(b,"ytp-ce-shown");k4(this,c.impressionUrls);(b=g.pC())&&g.sM(b,c.visualElement);this.player.V().D&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.po(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.po(b,"ytp-ce-shown");this.player.V().D&&this.player.Oa("endscreenelementhidden",a)}};
g.k.i6=function(a){var b=this;a.target===window&&(new g.fo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.qo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var dab=[346,426,470,506,570,640,853,1280,1920],eab="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),gab=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],fab=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Z9a={Koa:"current",kNa:"new"};var a$a={CLOSE:"close",XQa:"openUrl",SUBSCRIBE:"subscribe"},b$a={Hja:"click",CLOSE:"close",Nya:"hidden",vWa:"rollOut",wWa:"rollOver",GYa:"shown"};d$a.prototype.Oe=function(){var a=e$a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var $$a={afa:"anchored",oX:"branding",CHANNEL:"channel",Aoa:"cta",Qya:"highlightText",ZCa:"label",PLAYLIST:"playlist",UTa:"popup",k0a:"speech",SUBSCRIBE:"subscribe",m3a:"title",VIDEO:"video",S9a:"website"},Z$a={oX:"branding",Jha:"card",Qqa:"drawer",Pya:"highlight",MIa:"marker",YUa:"promotion",TEXT:"text",xab:"widget"};g.w(r4,g.C);g.k=r4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.FB(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.Wa.set(a,e);this.context.F.De([a])};
g.k.DC=function(){this.context.u.subscribe("resize",this.SD,this)};
g.k.vb=function(){return this.element};
g.k.HH=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Me(this.vb())};
g.k.SD=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=m4(a);if(f){var h=l$a(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.cw(f||"");m&&n&&(n.v||n.list)?e.context.F.Xm(n.v,b,n.list,!1):g.ZK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);E4(this.context.logger,c,l,d);k$a(f)||(c=g.pC(),d=b.itct,c&&d&&g.vM(c,g.lC(d)))}};
g.k.ra=function(){this.Ya.clear();this.Wa.clear();g.C.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.w(n$a,r4);g.k=n$a.prototype;g.k.Jr=function(){this.oa&&w4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Nl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.SD=function(){var a=this.isAvailable();g.Ol(this.vb(),a);g.ro(this.context.F.getRootNode(),g.AW.IV_DRAWER_ENABLED,a);X3(this.F)};
g.k.destroy=function(){this.F.Hy(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.Mz(this.ea);g.sz(this.Aa);this.Va&&this.Va.dispose();this.D&&this.D.dispose();r4.prototype.destroy.call(this)};
g.k.A0=function(){if(this.B){E4(this.context.logger,B4(this).wi.close);var a=g.pC();a&&this.J&&g.vM(a,this.J);v4(this)}};
g.k.O0=function(){g.ro(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.J2=function(){var a=g.pC(),b=B4(this);b=b?b.Hf:this.Hf;a&&b&&g.tM(a,[b])};
g.k.I2=function(){var a=g.pC(),b=B4(this);b=b?b.Hf:this.Hf;a&&b&&g.uM(a,[b])};
g.k.SX=function(){var a=B4(this);E4(this.context.logger,a.wi.jW);var b=g.pC();b&&a&&g.tM(b,[a.Ek,a.Hf])};
g.k.K2=function(){var a=g.pC(),b=B4(this);a&&b&&g.uM(a,[b.Ek])};
g.k.RX=function(a){var b=B4(this),c=g.pC();this.j?a?(a=this.context.logger,E4(a,b.wi.TG),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Ek&&g.vM(c,b.Ek)):(a=this.context.logger,E4(a,b.wi.TG),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Hf&&g.vM(c,b.Hf)):(a=this.context.logger,E4(a,b.wi.TG),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Hf&&g.vM(c,this.Hf))};g.w(C4,r4);C4.prototype.DC=function(){r4.prototype.DC.call(this);C$a(this)};
C4.prototype.show=function(){r4.prototype.show.call(this);var a=g.pC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tM(a,[g.lC(b.itct)])};
C4.prototype.hide=function(){r4.prototype.hide.call(this);var a=g.pC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.uM(a,[g.lC(b.itct)])};g.w(D4,C4);
D4.prototype.show=function(){if(!this.isActive){C4.prototype.show.call(this);if(!this.J){g.no(this.vb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ha:["branding-img","iv-click-target"],X:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ol(this.u,!1);var b=this.createElement({G:"button",Ha:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.vb().appendChild(b);var c=this.annotation.Oe();c&&s4(this,
b,c,this.annotation.id,a.session_data);G$a(this,a);this.J=!0}g.Ol(this.vb(),!0);this.isActive=!0;this.u&&(D$a(this,this.u),g.no(this.context.F.getRootNode(),"ytp-branding-shown"))}};
D4.prototype.hide=function(){this.isActive&&(C4.prototype.hide.call(this),g.Ol(this.vb(),!1),this.isActive=!1,g.po(this.context.F.getRootNode(),"ytp-branding-shown"))};
D4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);C4.prototype.destroy.call(this)};g.w(I$a,C4);g.k=I$a.prototype;g.k.show=function(){this.isActive||(C4.prototype.show.call(this),this.Z||(K$a(this),this.Z=!0),g.Ol(this.vb(),!0),g.rf(function(){g.po(this.vb(),"iv-promo-inactive")},100,this),this.vb().removeAttribute("aria-hidden"),this.isActive=!0,O$a(this),L$a(this),M$a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.no(this.vb(),"iv-promo-inactive"),this.isActive=!1,this.vb().setAttribute("aria-hidden","true"))};
g.k.HH=function(a,b,c,d,e,f){return this.isCollapsed?!1:C4.prototype.HH.call(this,a,b,c,d,e,f)};
g.k.M1=function(a){this.T=!0;J$a(this,500,a)};
g.k.L1=function(){this.T=!1;N$a(this)};
g.k.G1=function(a){a.stopPropagation();this.hide()};
g.k.H1=function(a){a.stopPropagation();O$a(this);this.isCollapsed=!0;g.no(this.vb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();C4.prototype.destroy.call(this)};g.w(Q$a,g.gR);g.k=Q$a.prototype;g.k.Zg=function(a,b){if(!cab(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.t4a(b))&&U$a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(r$a(this.j,b),X3(this.player)),!0}return null};
g.k.getOptions=function(){return cab(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.yv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.Z||a.S("embeds_enable_muted_autoplay")&&this.player.isMutedByMutedAutoplay()?!1:1===c&&!b.QO||a.ya.get(b.videoId)||g.fK(b)||g.gK(b)?!0:!1};
g.k.SF=function(){if(this.B){var a=this.player.fb().getVideoContentRect(!0);g.Ml(this.B.element,a.width,a.height);g.Il(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Xj();a=this.j;b=b.width;g.ro(a.C,"iv-drawer-small",426>=b);g.ro(a.C,"iv-drawer-big",1280<=b)}};
g.k.TX=function(a){S$a(this,a.state);g.S(a.state,2)&&(this.dj()&&this.Hn()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hy(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.kw(h)&&h.responseXML?h.responseXML:null)&&(U$a(b,h),g.no(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.gR.prototype.load.call(this);S$a(this,this.player.Fb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rx()&&(a=V$a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().ya.get(d);f&&W$a(e,f);f=f&&(f.YD||f.fA);if(!c.mz||f)c.Ya?this.C=g.qw(c.Ya,e):(this.Mo=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Mo));
g.yQ(this.player,this.B.element,4);this.SF();(f=g.fK(c))&&aab(this,f);(f=g.gK(c))&&f.featuredChannel&&bab(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ya&&(this.Mo&&(this.player.removeEventListener("videodatachange",this.Mo),this.Mo=null),this.C=g.qw(b.Ya,a))};
g.k.unload=function(){this.player.Mf("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,X3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.gR.prototype.unload.call(this);this.B.detach();this.Mo&&(this.player.removeEventListener("videodatachange",this.Mo),this.Mo=null)};
g.k.OU=function(a){a===this.player.getVideoData().videoId&&(this.loaded?X$a(this):this.load())};
g.k.dj=function(){return!!this.j&&this.j.isAvailable()};
g.k.Hn=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.dj();this.j&&(a?c?u4(this.j,c,b):u4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):v4(this.j))};
g.k.Hy=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().ya.unsubscribe("vast_info_card_add",this.OU,this);g.po(this.player.getRootNode(),g.AW.IV_DRAWER_OPEN);for(var a=this.T,b=g.ao,c=0,d=a.length;c<d;c++)b.Vl(a[c]);this.T.length=0;g.gR.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.D(this,a);return a.element};g.fR("annotations_module",Q$a);g.fR("creatorendscreen",K9a);})(_yt_player);
