(function(g){var window=this;'use strict';var odb=function(a){g.V.call(this,{G:"div",K:"ytp-miniplayer-ui"});this.If=!1;this.player=a;this.N(a,"minimized",this.Fh);this.N(a,"onStateChange",this.QN)},pdb=function(a){g.gR.call(this,a);
this.u=new g.GF(this);this.j=new odb(this.player);this.j.hide();g.yQ(this.player,this.j.element,4);a.Xf()&&(this.load(),g.ro(a.getRootNode(),"ytp-player-minimized",!0));this.player.S("web_rounded_containers")&&g.ro(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.w(odb,g.V);g.k=odb.prototype;
g.k.SK=function(){this.tooltip=new g.mV(this.player,this);g.D(this,this.tooltip);g.yQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Oc=new g.aS(this.player);g.D(this,this.Oc);this.Ui=new g.V({G:"div",K:"ytp-miniplayer-scrim"});g.D(this,this.Ui);this.Ui.Ea(this.element);this.N(this.Ui.element,"click",this.TF);var a=new g.V({G:"button",Ha:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Cerrar"},W:[g.vN()]});g.D(this,a);a.Ea(this.Ui.element);this.N(a.element,"click",this.zo);
a=new g.D2(this.player,this);g.D(this,a);a.Ea(this.Ui.element);this.Ot=new g.V({G:"div",K:"ytp-miniplayer-controls"});g.D(this,this.Ot);this.Ot.Ea(this.Ui.element);this.N(this.Ot.element,"click",this.TF);var b=new g.V({G:"div",K:"ytp-miniplayer-button-container"});g.D(this,b);b.Ea(this.Ot.element);a=new g.V({G:"div",K:"ytp-miniplayer-play-button-container"});g.D(this,a);a.Ea(this.Ot.element);var c=new g.V({G:"div",K:"ytp-miniplayer-button-container"});g.D(this,c);c.Ea(this.Ot.element);this.dV=new g.GT(this.player,
this,!1);g.D(this,this.dV);this.dV.Ea(b.element);b=new g.ET(this.player,this);g.D(this,b);b.Ea(a.element);this.nextButton=new g.GT(this.player,this,!0);g.D(this,this.nextButton);this.nextButton.Ea(c.element);this.Xi=new g.$U(this.player,this);g.D(this,this.Xi);this.Xi.Ea(this.Ui.element);this.Hc=new g.RT(this.player,this);g.D(this,this.Hc);g.yQ(this.player,this.Hc.element,4);this.JF=new g.V({G:"div",K:"ytp-miniplayer-buttons"});g.D(this,this.JF);g.yQ(this.player,this.JF.element,4);a=new g.V({G:"button",
Ha:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Cerrar"},W:[g.vN()]});g.D(this,a);a.Ea(this.JF.element);this.N(a.element,"click",this.zo);a=new g.V({G:"button",Ha:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Cerrar"},W:[g.CN()]});g.D(this,a);a.Ea(this.JF.element);this.N(a.element,"click",this.k5);this.N(this.player,"presentingplayerstatechange",this.od);this.N(this.player,"appresize",this.Db);this.N(this.player,"fullscreentoggled",this.Db);this.Db()};
g.k.show=function(){this.Te=new g.co(this.Ou,null,this);this.Te.start();this.If||(this.SK(),this.If=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Hc.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.Te&&(this.Te.dispose(),this.Te=void 0);g.V.prototype.hide.call(this);this.player.Xf()||(this.If&&this.Hc.hide(),this.player.loadModule("annotations_module"))};
g.k.ra=function(){this.Te&&(this.Te.dispose(),this.Te=void 0);g.V.prototype.ra.call(this)};
g.k.zo=function(){this.player.stopVideo();this.player.Oa("onCloseMiniplayer")};
g.k.k5=function(){this.player.playVideo()};
g.k.TF=function(a){if(a.target===this.Ui.element||a.target===this.Ot.element)g.aM(this.player.Fb())?this.player.pauseVideo():this.player.playVideo()};
g.k.Fh=function(){g.ro(this.player.getRootNode(),"ytp-player-minimized",this.player.Xf())};
g.k.Ae=function(){this.Hc.qc();this.Xi.qc()};
g.k.Ou=function(){this.Ae();this.Te&&this.Te.start()};
g.k.od=function(a){g.S(a.state,32)&&this.tooltip.hide()};
g.k.Db=function(){g.kU(this.Hc,0,this.player.fb().getPlayerSize().width,!1);g.UT(this.Hc)};
g.k.QN=function(a){this.player.Xf()&&(0===a?this.hide():this.show())};
g.k.zc=function(){return this.tooltip};
g.k.Wf=function(){return!1};
g.k.Sg=function(){return!1};
g.k.dk=function(){return!1};
g.k.jl=function(){return!1};
g.k.Je=function(){return!1};
g.k.BC=function(){};
g.k.rp=function(){};
g.k.ix=function(){};
g.k.jm=function(){return null};
g.k.EE=function(){return null};
g.k.WA=function(){return null};
g.k.Xj=function(){return new g.ul(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Yu=function(a,b,c,d,e){var f=0,h=d=0,l=g.Nl(a);if(b){c=g.mo(b,"ytp-prev-button")||g.mo(b,"ytp-next-button");var m=g.mo(b,"ytp-play-button"),n=g.mo(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Ll(b,this.element),h=b.x,f=b.y-12):n&&(h=g.mo(b,"ytp-miniplayer-button-top-left"),f=g.Ll(b,this.element),b=g.Nl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.fb().getPlayerSize().width;e=f+(e||0);l=g.Vd(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.Io=function(){};
g.k.al=function(){return!1};
g.k.CC=function(){};
g.k.Jy=function(){};
g.k.qq=function(){};
g.k.oq=function(){};
g.k.LD=function(){};
g.k.Zq=function(){};g.w(pdb,g.gR);g.k=pdb.prototype;g.k.onVideoDataChange=function(){if(this.player.S("web_rounded_containers")&&this.player.getVideoData()){var a=16/9;a=this.player.getVideoAspectRatio()>a+.1;g.ro(this.player.getRootNode(),"ytp-rounded-miniplayer-extra-wide-video",a)}};
g.k.create=function(){g.gR.prototype.create.call(this);this.u.N(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.zk=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.fR("miniplayer",pdb);})(_yt_player);
